version: "3.9"

services:
  app:
    build: .
    image: labyrinth-temporal-hunt:latest
    container_name: labyrinth-temporal-hunt
    env_file:
      - .env
    ports:
      - "8501:8501"
    restart: unless-stopped
